version: '3.8'

services:
  # PostgreSQL Veritabanı
  db:
    image: postgres:15-alpine
    container_name: node_api_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: node_api_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis (Cache için)
  redis:
    image: redis:7-alpine
    container_name: node_api_redis
    restart: always
    ports:
      - '6379:6379'

volumes:
  postgres_data:
